# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f28e85a69be247229db82dcf481087d2b4fc8690b49c563307701bd9282b3bc4b42f99a50f7073c0e1239e8c36ba924f0780184fbee04afb2f09f60b7202a08

test:
  secret_key_base: 6969fbfc5b250f11e26cd3b47501ad68202d3c3e8414f0d549765264fc6d71b6b2e862895776ab82dabd33bddbb0ca7f66ced3ecca17b0e3b56d97b3f340abfe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
